-- List all customers who have made purchases of more than $80.

select * from orders where total_amount > 80;

-- Retrieve all orders placed in the last 280 days along with the customer name and email.

select users.user_id,users.user_name,users.email_id,orders.order_id,orders.order_date,orders.total_amount from
	   orders join users on orders.user_id=users.user_id where orders.order_date between '2024-03-01' and '2025-01-01';

-- Find the average product price for each category.

select category,avg(price) as total_price from products group by category; 
 
-- List all customers who have purchased a product from the category Electronics.

select * from products where category='Electronics'; 

-- Find the total number of products sold and the total revenue generated for each product.   

select sum(orderdetails.quantity) as total_quantity,sum(orderdetails.quantity*products.price) as product_price from 
orderdetails join products on orderdetails.product_id=products.product_id group by orderdetails.product_id 
order by product_price desc;
set sql_safe_updates=0;
-- Update the price of all products in the Books category, increasing it by 10%.

update products set price=price+(price*.10) where category='Books';

select * from products;

-- Remove all orders that were placed before 2020.
delete from orders where order_date<'2020-01-01';

-- Write a query to fetch the order details, including customer name, product name, and quantity, for orders placed on 2024-05-01.

select orderdetails.quantity,orders.user_id,orders.order_date,orderdetails.product_id,products.prod_name,users.user_name
from orderdetails join orders on orderdetails.order_id=orders.order_id 
join products on  orderdetails.product_id=products.product_id 
join users on orders.user_id=users.user_id where orders.order_date='2024-05-01';

--  Fetch all customers and the total number of orders they have placed.

select users.user_name,count(orders.order_id) from users left join orders on users.user_id=orders.user_id group by users.user_name;

--  List all customers who purchased more than 1 units of any product, including the product name and total quantity purchased.

select orderdetails.order_id,orderdetails.product_id,orderdetails.quantity,orders.user_id,users.user_name from orderdetails join orders
on orderdetails.order_id=orders.order_id 
join users on orders.user_id=users.user_id where orderdetails.quantity > 1;

-- Find the total revenue generated by each category along with the category name.

select products.category,sum(orderdetails.quantity * products.price) from orderdetails 
join products on orderdetails.product_id=products.product_id group by products.category;

select * from products;